static const AVCodec * const codec_list[] = {
    &ff_aac_decoder,
    &ff_ac3_decoder,
    &ff_alac_decoder,
    &ff_amrnb_decoder,
    &ff_amrwb_decoder,
    &ff_dca_decoder,
    &ff_eac3_decoder,
    &ff_flac_decoder,
    &ff_mlp_decoder,
    &ff_mp3_decoder,
    &ff_opus_decoder,
    &ff_truehd_decoder,
    &ff_vorbis_decoder,
    &ff_pcm_alaw_decoder,
    &ff_pcm_mulaw_decoder,
    NULL };
